version: "3"

services:
  mysql:
    restart: on-failure
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql-data:/var/lib/mysql"
    env_file:
      - ./secrets/mysql.env
    ports:
      - "3306:3306"

  mongodb:
    restart: on-failure
    image: mongo
    env_file:
      - ./secrets/mongo.env
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-data:/data/db"

  caddy:
    restart: on-failure
    image: "caddy"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./qaq-react:/webpage"
    networks:
      - qaq-net
    ports:
      - 3000:3000
    
networks:
  qaq-net:
